
#version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: kyle1234
      MYSQL_DATABASE: qap2sdat
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kyle1234
      MYSQL_DATABASE: qap2sdat
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: